equipment:
  switches:
    access:
      Acc-SW1:
        interfaces:
          accessMode:
            g0/3:
              vlanNo: 100
            g1/0:
              vlanNo: 200
          trunkMode:
            g0/0:
              desc: "Acc-SW1 to Dist-SW1"
              vlanNo: "100,200"
            g0/1:
              desc: "Acc-SW1 to Dist-SW2"
              vlanNo: "100,200"
      Acc-SW2:
        interfaces:
          accessMode:
            g0/3:
              vlanNo: 100
            g1/0:
              vlanNo: 200
          trunkMode:
            g0/0:
              desc: "Acc-SW2 to Dist-SW1"
              vlanNo: "100,200"
            g0/1:
              desc: "Acc-SW2 to Dist-SW2"
              vlanNo: "100,200"
      Acc-SW3:
        interfaces:
          accessMode:
            g0/3:
              vlanNo: 100
            g1/0:
              vlanNo: 200
          trunkMode:
            g0/0:
              desc: "Acc-SW3 to Dist-SW3"
              vlanNo: "100,200"
            g0/1:
              desc: "Acc-SW3 to Dist-SW4"
              vlanNo: "100,200"
      Acc-SW4:
        interfaces:
          accessMode:
            g0/3:
              vlanNo: 100
            g1/0:
              vlanNo: 200
          trunkMode:
            g0/0:
              desc: "Acc-SW4 to Dist-SW3"
              vlanNo: "100,200"
            g0/1:
              desc: "Acc-SW4 to Dist-SW4"
              vlanNo: "100,200"
    distribution:
      Dist-SW1:
        interfaces:
          trunkMode:
            g1/0:
              desc: "Dist-SW1 to Acc-SW1"
              vlanNo: "100,200"
            g1/1:
              desc: "Dist-SW1 to Acc-SW2"
              vlanNo: "100,200"
          vlan:
            100:
              ip: "10.1.100.2"
              subnet: "255.255.255.0"
              standbyNo: 10
              standbyIP: "10.1.100.1"
              standbyPrio: 110
            200:
              ip: "10.1.200.2"
              subnet: "255.255.255.0"
              standbyNo: 20
              standbyIP: "10.1.200.1"
              standbyPrio: 100
          etherchannel:
            g0/2-3:
              ip: "10.1.2.1"
              subnet: "255.255.255.252"
          layer3:
            g0/0:
              desc: "Dist-SW1 to Core-R1"
              ip: "10.1.3.1"
              subnet: "255.255.255.252"
            g0/1:
              desc: "Dist-SW1 to Core-R2"
              ip: "10.1.3.13"
              subnet: "255.255.255.252"
          loopback:
            loopback0:
              ip: "10.255.0.1"
              subnet: "255.255.255.255"
        ospf:
          network:
            network1:
              ip: "10.1.2.0"
              wildcard: "0.0.0.3"
            network2:
              ip: "10.1.3.0"
              wildcard: "0.0.0.255"
            network3:
              ip: "10.1.100.0"
              wildcard: "0.0.0.255"
            network4:
              ip: "10.1.200.0"
              wildcard: "0.0.0.255"
            network5:
              ip: "10.255.0.1"
              wildcard: "0.0.0.0"
      Dist-SW2:
        interfaces:
          trunkMode:
            g1/0:
              desc: "Dist-SW2 to Acc-SW1"
              vlanNo: "100,200"
            g1/1:
              desc: "Dist-SW2 to Acc-SW2"
              vlanNo: "100,200"
          vlan:
            100:
              ip: "10.1.100.3"
              subnet: "255.255.255.0"
              standbyNo: 10
              standbyIP: "10.1.100.1"
              standbyPrio: 100
            200:
              ip: "10.1.200.3"
              subnet: "255.255.255.0"
              standbyNo: 20
              standbyIP: "10.1.200.1"
              standbyPrio: 110
          etherchannel:
            g0/2-3:
              ip: "10.1.2.2"
              subnet: "255.255.255.252"
          layer3:
            g0/0:
              desc: "Dist-SW2 to Core-R1"
              ip: "10.1.3.9"
              subnet: "255.255.255.252"
            g0/1:
              desc: "Dist-SW2 to Core-R2"
              ip: "10.1.3.5"
              subnet: "255.255.255.252"
          loopback:
            loopback0:
              ip: "10.255.0.2"
              subnet: "255.255.255.255"
        ospf:
          network:
            network1:
              ip: "10.1.2.0"
              wildcard: "0.0.0.3"
            network2:
              ip: "10.1.3.0"
              wildcard: "0.0.0.255"
            network3:
              ip: "10.1.100.0"
              wildcard: "0.0.0.255"
            network4:
              ip: "10.1.200.0"
              wildcard: "0.0.0.255"
            network5:
              ip: "10.255.0.2"
              wildcard: "0.0.0.0"
      Dist-SW3:
        interfaces:
          trunkMode:
            g1/0:
              desc: "Dist-SW3 to Acc-SW3"
              vlanNo: "100,200"
            g1/1:
              desc: "Dist-SW3 to Acc-SW4"
              vlanNo: "100,200"
          vlan:
            100:
              ip: "10.2.100.2"
              subnet: "255.255.255.0"
              standbyNo: 10
              standbyIP: "10.1.100.1"
              standbyPrio: 110
            200:
              ip: "10.2.200.2"
              subnet: "255.255.255.0"
              standbyNo: 20
              standbyIP: "10.2.200.1"
              standbyPrio: 100
          etherchannel:
            g0/2-3:
              ip: "10.2.2.1"
              subnet: "255.255.255.252"
          layer3:
            g0/0:
              desc: "Dist-SW3 to Core-R1"
              ip: "10.2.3.1"
              subnet: "255.255.255.252"
            g0/1:
              desc: "Dist-SW3 to Core-R2"
              ip: "10.2.3.13"
              subnet: "255.255.255.252"
          loopback:
            loopback0:
              ip: "10.255.2.1"
              subnet: "255.255.255.255"
        ospf:
          network:
            network1:
              ip: "10.2.2.0"
              wildcard: "0.0.0.3"
            network2:
              ip: "10.2.3.0"
              wildcard: "0.0.0.255"
            network3:
              ip: "10.2.100.0"
              wildcard: "0.0.0.255"
            network4:
              ip: "10.2.200.0"
              wildcard: "0.0.0.255"
            network5:
              ip: "10.255.2.1"
              wildcard: "0.0.0.0"
      Dist-SW4:
        interfaces:
          trunkMode:
            g1/0:
              desc: "Dist-SW4 to Acc-SW3"
              vlanNo: "100,200"
            g1/1:
              desc: "Dist-SW4 to Acc-SW4"
              vlanNo: "100,200"
          vlan:
            100:
              ip: "10.2.100.3"
              subnet: "255.255.255.0"
              standbyNo: 10
              standbyIP: "10.2.100.1"
              standbyPrio: 100
            200:
              ip: "10.2.200.3"
              subnet: "255.255.255.0"
              standbyNo: 20
              standbyIP: "10.2.200.1"
              standbyPrio: 110
          etherchannel:
            g0/2-3:
              ip: "10.2.2.2"
              subnet: "255.255.255.252"
          layer3:
            g0/0:
              desc: "Dist-SW4 to Core-R1"
              ip: "10.2.3.9"
              subnet: "255.255.255.252"
            g0/1:
              desc: "Dist-SW4 to Core-R2"
              ip: "10.2.3.5"
              subnet: "255.255.255.252"
          loopback:
            loopback0:
              ip: "10.255.2.2"
              subnet: "255.255.255.255"
        ospf:
          network:
            network1:
              ip: "10.2.2.0"
              wildcard: "0.0.0.3"
            network2:
              ip: "10.2.3.0"
              wildcard: "0.0.0.255"
            network3:
              ip: "10.2.100.0"
              wildcard: "0.0.0.255"
            network4:
              ip: "10.2.200.0"
              wildcard: "0.0.0.255"
            network5:
              ip: "10.255.2.2"
              wildcard: "0.0.0.0"
  routers: 
    core:
      Core-R1:
        interfaces:
          layer3:
            g0/0:
              desc: "Core-R1 to Core-R2"
              ip: "10.1.1.1"
              subnet: "255.255.255.252"
            g0/1:
              desc: "Core-R1 to Dist-SW1"
              ip: "10.1.3.2"
              subnet: "255.255.255.252"
            g0/2:
              desc: "Core-R1 to Dist-SW2"
              ip: "10.1.3.10"
              subnet: "255.255.255.252"
            g0/3:
              desc: "Core-R1 to Dist-SW3"
              ip: "10.2.3.2"
              subnet: "255.255.255.252"
            g0/4:
              desc: "Core-R1 to Dist-SW4"
              ip: "10.2.3.10"
              subnet: "255.255.255.252"
            g0/5:
              desc: "Core-R1 to CE1"
              ip: "10.1.0.2"
              subnet: "255.255.255.252"
          loopback:
            loopback0:
              ip: "10.255.0.3"
              subnet: "255.255.255.255"
        ospf:
          network:
            network1:
              ip: "10.1.1.0"
              wildcard: "0.0.0.3"
            network2:
              ip: "10.1.3.0"
              wildcard: "0.0.0.255"
            network3:
              ip: "10.1.0.0"
              wildcard: "0.0.0.255"
            network4:
              ip: "10.2.3.0"
              wildcard: "0.0.0.255"
            network5:
              ip: "10.255.0.3"
              wildcard: "0.0.0.0"
      Core-R2:
        interfaces:
          layer3:
            g0/0:
              desc: "Core-R2 to Core-R1"
              ip: "10.1.1.2"
              subnet: "255.255.255.252"
            g0/1:
              desc: "Core-R2 to Dist-SW1"
              ip: "10.1.3.14"
              subnet: "255.255.255.252"
            g0/2:
              desc: "Core-R2 to Dist-SW2"
              ip: "10.1.3.6"
              subnet: "255.255.255.252"
            g0/3:
              desc: "Core-R2 to Dist-SW3"
              ip: "10.2.3.14"
              subnet: "255.255.255.252"
            g0/4:
              desc: "Core-R2 to Dist-SW4"
              ip: "10.2.3.6"
              subnet: "255.255.255.252"
            g0/5:
              desc: "Core-R2 to CE1"
              ip: "10.1.0.6"
              subnet: "255.255.255.252"
          loopback:
            loopback0:
              ip: "10.255.0.4"
              subnet: "255.255.255.255"
        ospf:
          network:
            network1:
              ip: "10.1.1.0"
              wildcard: "0.0.0.3"
            network2:
              ip: "10.1.3.0"
              wildcard: "0.0.0.255"
            network3:
              ip: "10.1.0.0"
              wildcard: "0.0.0.255"
            network4:
              ip: "10.2.3.0"
              wildcard: "0.0.0.255"
            network5:
              ip: "10.255.0.4"
              wildcard: "0.0.0.0"
    edge:
      CE1:
        interfaces:
          layer3:
            g0/0:
              desc: "CE1 to PE1"
              ip: "172.16.1.2"
              subnet: "255.255.255.252"
            g0/1:
              desc: "CE1 to Core-R1"
              ip: "10.1.0.1"
              subnet: "255.255.255.252"
            g0/2:
              desc: "CE1 to Core-R2"
              ip: "10.1.0.5"
              subnet: "255.255.255.252"
          loopback:
            loopback0:
              ip: "10.255.0.100"
              subnet: "255.255.255.255"
        ospf:
          network:
            network1:
              ip: "10.1.0.0"
              wildcard: "0.0.0.255"
            network2:
              ip: "10.2.0.0"
              wildcard: "0.0.0.255"
            network3:
              ip: "10.255.0.100"
              wildcard: "0.0.0.0"
        bgp:
          neighbor:
            neighbor1:
              ip: "172.16.1.1"
              asNo: 65000
          network:
            network1:
              ip: "172.16.1.0"
              subnet: "255.255.255.252"
            network2:
              ip: "10.1.100.0"
              subnet: "255.255.255.0"
            network3:
              ip: "10.1.200.0"
              subnet: "255.255.255.0"
            network4:
              ip: "10.2.100.0"
              subnet: "255.255.255.0"
            network5:
              ip: "10.2.200.0"
              subnet: "255.255.255.0"
        default:
          ip: "172.16.1.1"


              

