equipment:
  switches:
    access:
      Acc-SW5:
        interfaces:
          accessMode:
            g0/3:
              vlanNo: 100
            g1/0:
              vlanNo: 200
          trunkMode:
            g0/0:
              desc: "Acc-SW5 to Dist-SW5"
              vlanNo: "100,200"
            g0/1:
              desc: "Acc-SW5 to Dist-SW6"
              vlanNo: "100,200"
      Acc-SW6:
        interfaces:
          accessMode:
            g0/3:
              vlanNo: 100
            g1/0:
              vlanNo: 200
          trunkMode:
            g0/0:
              desc: "Acc-SW6 to Dist-SW5"
              vlanNo: "100,200"
            g0/1:
              desc: "Acc-SW6 to Dist-SW6"
              vlanNo: "100,200"

    distribution:
      Dist-SW5:
        interfaces:
          trunkMode:
            g1/0:
              desc: "Dist-SW5 to Acc-SW5"
              vlanNo: "100,200"
            g1/1:
              desc: "Dist-SW5 to Acc-SW6"
              vlanNo: "100,200"
          vlan:
            100:
              ip: "10.3.100.2"
              subnet: "255.255.255.0"
              standbyNo: 10
              standbyIP: "10.3.100.1"
              standbyPrio: 110
            200:
              ip: "10.3.200.2"
              subnet: "255.255.255.0"
              standbyNo: 20
              standbyIP: "10.3.200.1"
              standbyPrio: 100
          etherchannel:
            g0/2-3:
              ip: "10.3.2.1"
              subnet: "255.255.255.252"
          layer3:
            g0/0:
              desc: "Dist-SW5 to Core-R3"
              ip: "10.3.3.1"
              subnet: "255.255.255.252"
            g0/1:
              desc: "Dist-SW5 to Core-R4"
              ip: "10.3.3.13"
              subnet: "255.255.255.252"
          loopback:
            loopback0:
              ip: "10.255.3.1"
              subnet: "255.255.255.255"
        ospf:
          network:
            network1:
              ip: "10.3.2.0"
              wildcard: "0.0.0.3"
            network2:
              ip: "10.3.3.0"
              wildcard: "0.0.0.255"
            network3:
              ip: "10.3.100.0"
              wildcard: "0.0.0.255"
            network4:
              ip: "10.3.200.0"
              wildcard: "0.0.0.255"
            network5:
              ip: "10.255.3.1"
              wildcard: "0.0.0.0"
      Dist-SW6:
        interfaces:
          trunkMode:
            g1/0:
              desc: "Dist-SW6 to Acc-SW5"
              vlanNo: "100,200"
            g1/1:
              desc: "Dist-SW6 to Acc-SW6"
              vlanNo: "100,200"
          vlan:
            100:
              ip: "10.3.100.3"
              subnet: "255.255.255.0"
              standbyNo: 10
              standbyIP: "10.3.100.1"
              standbyPrio: 100
            200:
              ip: "10.3.200.3"
              subnet: "255.255.255.0"
              standbyNo: 20
              standbyIP: "10.3.200.1"
              standbyPrio: 110
          etherchannel:
            g0/2-3:
              ip: "10.3.2.2"
              subnet: "255.255.255.252"
          layer3:
            g0/0:
              desc: "Dist-SW6 to Core-R3"
              ip: "10.3.3.9"
              subnet: "255.255.255.252"
            g0/1:
              desc: "Dist-SW6 to Core-R4"
              ip: "10.3.3.5"
              subnet: "255.255.255.252"
          loopback:
            loopback0:
              ip: "10.255.3.2"
              subnet: "255.255.255.255"
        ospf:
          network:
            network1:
              ip: "10.3.2.0"
              wildcard: "0.0.0.3"
            network2:
              ip: "10.3.3.0"
              wildcard: "0.0.0.255"
            network3:
              ip: "10.3.100.0"
              wildcard: "0.0.0.255"
            network4:
              ip: "10.3.200.0"
              wildcard: "0.0.0.255"
            network5:
              ip: "10.255.3.2"
              wildcard: "0.0.0.0"
  routers: 
    core:
      Core-R3:
        interfaces:
          layer3:
            g0/0:
              desc: "Core-R3 to Core-R4"
              ip: "10.3.1.1"
              subnet: "255.255.255.252"
            g0/1:
              desc: "Core-R3 to Dist-SW5"
              ip: "10.3.3.2"
              subnet: "255.255.255.252"
            g0/2:
              desc: "Core-R3 to Dist-SW6"
              ip: "10.3.3.10"
              subnet: "255.255.255.252"
            g0/3:
              desc: "Core-R3 to CE2"
              ip: "10.3.0.2"
              subnet: "255.255.255.252"
          loopback:
            loopback0:
              ip: "10.255.3.3"
              subnet: "255.255.255.255"
        ospf:
          network:
            network1:
              ip: "10.3.1.0"
              wildcard: "0.0.0.3"
            network2:
              ip: "10.3.3.0"
              wildcard: "0.0.0.255"
            network3:
              ip: "10.3.0.0"
              wildcard: "0.0.0.255"
            network4:
              ip: "10.255.3.3"
              wildcard: "0.0.0.0"
      Core-R4:
        interfaces:
          layer3:
            g0/0:
              desc: "Core-R4 to Core-R3"
              ip: "10.3.1.2"
              subnet: "255.255.255.252"
            g0/1:
              desc: "Core-R4 to Dist-SW5"
              ip: "10.3.3.14"
              subnet: "255.255.255.252"
            g0/2:
              desc: "Core-R4 to Dist-SW6"
              ip: "10.3.3.6"
              subnet: "255.255.255.252"
            g0/3:
              desc: "Core-R4 to CE2"
              ip: "10.3.0.6"
              subnet: "255.255.255.252"
          loopback:
            loopback0:
              ip: "10.255.3.4"
              subnet: "255.255.255.255"
        ospf:
          network:
            network1:
              ip: "10.3.1.0"
              wildcard: "0.0.0.3"
            network2:
              ip: "10.3.3.0"
              wildcard: "0.0.0.255"
            network3:
              ip: "10.3.0.0"
              wildcard: "0.0.0.255"
            network4:
              ip: "10.255.3.4"
              wildcard: "0.0.0.0"
    edge:
      CE2:
        interfaces:
          layer3:
            g0/0:
              desc: "CE2 to PE2"
              ip: "172.16.2.2"
              subnet: "255.255.255.252"
            g0/1:
              desc: "CE2 to Core-R3"
              ip: "10.3.0.1"
              subnet: "255.255.255.252"
            g0/2:
              desc: "CE2 to Core-R4"
              ip: "10.3.0.5"
              subnet: "255.255.255.252"
          loopback:
            loopback0:
              ip: "10.255.0.101"
              subnet: "255.255.255.255"
        ospf:
          network:
            network1:
              ip: "10.3.0.0"
              wildcard: "0.0.0.255"
            network2:
              ip: "10.255.0.101"
              wildcard: "0.0.0.0"
        bgp:
          neighbor:
            neighbor1:
              ip: "172.16.2.1"
              asNo: 65000
          network:
            network1:
              ip: "172.16.2.0"
              subnet: "255.255.255.252"
            network2:
              ip: "10.3.100.0"
              subnet: "255.255.255.0"
            network3:
              ip: "10.3.200.0"
              subnet: "255.255.255.0"
        default:
          ip: "172.16.2.1"


              

